name: avatar_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  model_viewer_plus: ^1.9.1
  flutter_gl: ^0.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.glb
    - assets/tex_u0_v0_diffuse.jpg
    - assets/tex_u0_v0_normal.jpg
    - assets/icons/favicon.ico
    - assets/icons/favicon-32x32.png
    - assets/icons/favicon-16x16.png
    - assets/icons/apple-touch-icon.png
    - assets/icons/android-chrome-512x512.png
    - assets/icons/android-chrome-192x192.png
